name: "Push docs to wiki"

on:
  push:
    branches:
      - main
    paths:
      - "docs/wiki/**"
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs/wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
